spring.datasource.url: jdbc:h2:file:./camunda-h2-database
firewareUrl: http://192.168.0.101:1026/v2/entities
subscriptionUrl: http://192.168.0.101:1026/v2/subscriptions
notificationUrl: http://192.168.0.101:8080/subscription
entityType: APMRobotProfile1, APMRobotProfile2, APMRobotProfile3, APMRobotProfile4, Test
camunda.bpm.admin-user:
  id: demo
  password: demo